site_name: Alex Aiken
site_author: Alex Aiken
site_description: "Alex Aiken's personal academic site (converted to MkDocs)"
site_url: "https://theory.stanford.edu/~aiken/"

extra_css:
  - stylessheet/theme2.css

nav:
  - Home: index.md
  - Contact: '/#contact'
  - FAQ: 'personal/faq.md'
  - Publications: 'publications/index.md'
  - Software: 'software/index.md'
  - Bio: '/#bio'
  - Teaching: '/#teaching'
  - Research: '#research'
  - Misc: '#misc'
  - Current Students: '#students'
  - Graduated Students: 'phds.md'

theme:
  name: material
  favicon: https://www-media.stanford.edu/assets/favicon/apple-touch-icon-57x57.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.expand
    - navigation.footer
    # - navigation.indexes
    - toc.integrate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      authors_file: .authors
  - glightbox
