site_name: Alex Aiken
site_author: Alex Aiken
site_description: "Alex Aiken's personal academic site (converted to MkDocs)"
repo_url: ''

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    # - toc.integrate

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      authors_file: .authors
  - glightbox

nav:
  - Contact: '/#contact'
  - FAQ: 'https://theory.stanford.edu/~aiken/personal/email.html'
  - Publications: 'https://theory.stanford.edu/~aiken/publications/publications.html'
  - Software: 'https://theory.stanford.edu/~aiken/personal/software.html'
  - Bio: 'bio.md'
  - Teaching: 'teaching.md'
  - Research: 'research.md'
  - Misc: 'misc.md'
  - Current Students: 'students.md'
  - Graduated Students: 'https://theory.stanford.edu/~aiken/phds.html'
